#!/bin/bash
# Skript kontrollib käsurea parameetri paarsust cut käsuga

# 1. Kontrollime, et parameetreid oleks täpselt 1
if [ $# -ne 1 ]; then
    echo "Käivita see skript koos arvuga mille paarsus soovid kontrollida. Näiteks: ./paarsus 3"
    exit
fi

# 2. Võtame arvu viimase numbri cut abil
viimane=$(echo $1 | cut -c -1)

# 3. Kontrollime, kas viimane number on paaris
if [ $viimane -eq 0 ] || [ $viimane -eq 2 ] || [ $viimane -eq 4 ] || [ $viimane -eq 6 ] || [ $viimane -eq 8 ]; then
    echo "Antud arv on paaris"
else
    echo "Antud arv on paaritu"
fi
