#!/bin/bash
# Skript kontrollib käsurea parameetripaarsust matemaatilise jäägiga

# Kontrollime, et parameetreid oleks täpselt 1
if [ $# -ne 1 ]; then
    echo "Käivita see skript koos arvuga mille paarsus soovid kontrollida. Näiteks: ./paarsus 3"
    exit
fi

# Arvutame 2-ga jagamise jäägi otse käsurea parameetrist $1
jaak=`expr $1 % 2`

if [ $jaak -eq 0 ]; then
    echo "Antud arv on paaris"
else
    echo "Antud arv on paaritu"
fi
